USE [master]
GO
/****** Object:  Database [Template]    Script Date: 18/06/2021 13:44:56 ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'Template')
BEGIN
CREATE DATABASE [Template]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Template', FILENAME = N'D:\SQLServer2019\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\Template.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Template_log', FILENAME = N'D:\SQLServer2019\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\Template_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
END
GO
ALTER DATABASE [Template] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Template].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Template] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Template] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Template] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Template] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Template] SET ARITHABORT OFF 
GO
ALTER DATABASE [Template] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Template] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Template] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Template] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Template] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Template] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Template] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Template] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Template] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Template] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Template] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Template] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Template] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Template] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Template] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Template] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Template] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Template] SET RECOVERY FULL 
GO
ALTER DATABASE [Template] SET  MULTI_USER 
GO
ALTER DATABASE [Template] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Template] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Template] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Template] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Template] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Template] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Template', N'ON'
GO
ALTER DATABASE [Template] SET QUERY_STORE = OFF
GO
USE [Template]
GO
/****** Object:  Table [dbo].[User]    Script Date: 18/06/2021 13:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[User]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[Role] [tinyint] NOT NULL,
	[Token] [nvarchar](max) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET IDENTITY_INSERT [dbo].[User] ON 
GO
INSERT [dbo].[User] ([ID], [Username], [Password], [Role], [Token]) VALUES (1, N'admin', N'123', 1, NULL)
GO
SET IDENTITY_INSERT [dbo].[User] OFF
GO
USE [master]
GO
ALTER DATABASE [Template] SET  READ_WRITE 
GO
