USE [master]
GO
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'TemplateMaster')
BEGIN
CREATE DATABASE [TemplateMaster]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TemplateMaster', FILENAME = N'D:\SQLServer2019\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\TemplateMaster.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TemplateMaster_log', FILENAME = N'D:\SQLServer2019\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\TemplateMaster.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
END
GO
ALTER DATABASE [TemplateMaster] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TemplateMaster].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TemplateMaster] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TemplateMaster] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TemplateMaster] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TemplateMaster] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TemplateMaster] SET ARITHABORT OFF 
GO
ALTER DATABASE [TemplateMaster] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TemplateMaster] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TemplateMaster] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TemplateMaster] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TemplateMaster] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TemplateMaster] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TemplateMaster] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TemplateMaster] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TemplateMaster] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TemplateMaster] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TemplateMaster] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TemplateMaster] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TemplateMaster] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TemplateMaster] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TemplateMaster] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TemplateMaster] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TemplateMaster] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TemplateMaster] SET RECOVERY FULL 
GO
ALTER DATABASE [TemplateMaster] SET  MULTI_USER 
GO
ALTER DATABASE [TemplateMaster] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TemplateMaster] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TemplateMaster] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TemplateMaster] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TemplateMaster] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TemplateMaster] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TemplateMaster', N'ON'
GO
ALTER DATABASE [TemplateMaster] SET QUERY_STORE = OFF
GO
USE [TemplateMaster]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Enterprise]') AND type in (N'U'))
BEGIN
CREATE TABLE [Enterprise](
	[ID] [uniqueidentifier] NOT NULL,
	[EnterpriseName] [varchar](150) NOT NULL,
	[ConnectionString] [varchar](max) NOT NULL,
	[NormalizedEnterprisename] [varchar](150) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Tenant]') AND type in (N'U'))
BEGIN
CREATE TABLE [Tenant](
	[ID] [uniqueidentifier] NOT NULL,
	[Logon] [varchar](200) NOT NULL,
	[Salt] [varchar](max) NOT NULL,
	[Password] [varchar](max) NOT NULL,
	[Role] [smallint] NOT NULL,
	[EnterpriseID] [uniqueidentifier] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
INSERT [Enterprise] ([ID], [EnterpriseName], [ConnectionString], [NormalizedEnterprisename]) VALUES (N'5ad5561f-84de-eb11-915d-18c04df0370d', N'Teste1', N'Server=ARTHUR-PC\MSSQLSERVER2019;Database=Template_TESTE1;User Id=sa;Password=testes@123;', N'TESTE1')
GO
INSERT [Enterprise] ([ID], [EnterpriseName], [ConnectionString], [NormalizedEnterprisename]) VALUES (N'5bd5561f-84de-eb11-915d-18c04df0370d', N'Teste2', N'Server=ARTHUR-PC\MSSQLSERVER2019;Database=Template_TESTE2;User Id=sa;Password=testes@123;', N'TESTE2')
GO
INSERT [Tenant] ([ID], [Logon], [Salt], [Password], [Role], [EnterpriseID]) VALUES (N'9dea7866-84de-eb11-915d-18c04df0370d', N'teste123@teste.com', N'bH3r1M82jke40KDZMWOmWQ==', N'R6DJgA3OdamUVliJvtbp/H0CKV+O6PqG', 1, N'5ad5561f-84de-eb11-915d-18c04df0370d')
GO
INSERT [Tenant] ([ID], [Logon], [Salt], [Password], [Role], [EnterpriseID]) VALUES (N'6136ed81-84de-eb11-915d-18c04df0370d', N'teste@teste.com', N'qaPWgysBvf75EMZILzQX8Q==', N'n+1jPyhzUrE4r6QAbbPdwQEciGuIsH15', 1, N'5bd5561f-84de-eb11-915d-18c04df0370d')
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DF_Enterprise_ID]') AND type = 'D')
BEGIN
ALTER TABLE [Enterprise] ADD  CONSTRAINT [DF_Enterprise_ID]  DEFAULT (newsequentialid()) FOR [ID]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DF_Tenant_ID]') AND type = 'D')
BEGIN
ALTER TABLE [Tenant] ADD  CONSTRAINT [DF_Tenant_ID]  DEFAULT (newsequentialid()) FOR [ID]
END
GO
USE [master]
GO
ALTER DATABASE [TemplateMaster] SET  READ_WRITE 
GO
