USE [master]
GO
/****** Object:  Database [Template_TESTE2]    Script Date: 06/07/2021 16:21:20 ******/
CREATE DATABASE [Template_TESTE2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Template_TESTE2', FILENAME = N'D:\SQLServer2019\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\Template_TESTE2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Template_TESTE2_log', FILENAME = N'D:\SQLServer2019\MSSQL15.MSSQLSERVER2019\MSSQL\DATA\Template_TESTE2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Template_TESTE2] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Template_TESTE2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Template_TESTE2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Template_TESTE2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Template_TESTE2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Template_TESTE2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Template_TESTE2] SET ARITHABORT OFF 
GO
ALTER DATABASE [Template_TESTE2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Template_TESTE2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Template_TESTE2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Template_TESTE2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Template_TESTE2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Template_TESTE2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Template_TESTE2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Template_TESTE2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Template_TESTE2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Template_TESTE2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Template_TESTE2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Template_TESTE2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Template_TESTE2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Template_TESTE2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Template_TESTE2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Template_TESTE2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Template_TESTE2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Template_TESTE2] SET RECOVERY FULL 
GO
ALTER DATABASE [Template_TESTE2] SET  MULTI_USER 
GO
ALTER DATABASE [Template_TESTE2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Template_TESTE2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Template_TESTE2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Template_TESTE2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Template_TESTE2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Template_TESTE2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Template_TESTE2', N'ON'
GO
ALTER DATABASE [Template_TESTE2] SET QUERY_STORE = OFF
GO
USE [Template_TESTE2]
GO
/****** Object:  Table [dbo].[User]    Script Date: 06/07/2021 16:21:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[ID] [uniqueidentifier] NOT NULL,
	[Name] [varchar](150) NOT NULL
) ON [PRIMARY]
GO
INSERT [dbo].[User] ([ID], [Name]) VALUES (N'6136ed81-84de-eb11-915d-18c04df0370d', N'Teste')
GO
USE [master]
GO
ALTER DATABASE [Template_TESTE2] SET  READ_WRITE 
GO
